#!/bin/bash

#no screen saving
xset -dpms; xset s off
##set dpi before starting wm
#one monitor: xrandr --dpi 192
#xrandr --output DP-1 --dpi 192 --output HDMI-1 --auto --rotate normal --scale 1x1 --right-of DP-1
xrandr --output HDMI-2 --dpi 192 --output DP-2 --auto --scale 1.5x1.5 --right-of HDMI-2
#fix retarded pa again
#pulseaudio -k; pulseaudio --start
#map escape to caps
setxkbmap -option caps:escape
exec i3
#no screen saving
xset -dpms; xset s off
#mount afp server
sudo mount_afp 'afp://admin:[REDACTED]' [REDACTED]
#start at server for browser script
sudo atd
