syntax on
set encoding=utf-8
set clipboard=unnamedplus
set tabstop=8
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab
set number
set cursorline
set wildmenu
set showmatch
set incsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
set laststatus=2
nnoremap j gj
nnoremap k gk
nnoremap gV `[v`]
nnoremap <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
nnoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"

" imports digraphs for symbols
" that work in most linux fonts
source ~/.vimdgrc
