#!/usr/bin/fish

# provides the development environment i like depending on window size
set wid (tput cols)
set hgt (tput lines)
if test (count $argv) -gt 0
  cd ~/work/$argv[1] 2>/dev/null
end
if test $wid -gt 100
  tmux split-window -h
  tmux resize-pane -x 80
  tmux select-pane -L
  if test (count $argv) -gt 0
    cd ~/work/$argv[1] 2>/dev/null
  end
end
if test $wid -gt 170
  tmux split-window -h
  tmux select-pane -L
  tmux resize-pane -x (expr $wid - 162)
  if test (count $argv) -gt 0
    cd ~/work/$argv[1] 2>/dev/null
  end
end
if test $wid -gt 100
  tmux split-window -v "hdc"
  tmux resize-pane -y 24
  tmux swap-pane -t -1
  clear
  if test (count $argv) -gt 0
    cd ~/work/$argv[1] 2>/dev/null
  end
  cabal new-build
end
